# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# Base URL for GitHub Pages deployment
baseURL = "https://h-ngyen.github.io/Internship-report-aws/"

# Set default content language to Vietnamese
defaultContentLanguage = "vi"

# For search functionality
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "journeyoftheaverageguy@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

# Note: must be lowercase "languages"
[languages]

  [languages.vi]
  title = "Deploy Node.js với AWS Serverless"
  weight = 1
  languageName = "Tiếng Việt"
  # no need to repeat defaultContentLanguage here
  [[languages.vi.menu.shortcuts]]
  name = "<i class='fab fa-facebook'></i> AWS Study Group"
  identifier = "AWS Study Group FB"
  url = "https://www.facebook.com/groups/awsstudygroupfcj/"
  weight = 20
  
  [languages.en]
  title = "Internship Report"
  weight = 2
  languageName = "English"
  [[languages.en.menu.shortcuts]]
  name = "<i class='fab fa-facebook'></i> AWS Study Group"
  identifier = "AWS Study Group FB"
  url = "https://www.facebook.com/groups/awsstudygroupfcj/"
  weight = 20